org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false

# Release signing properties for android/app/build.gradle.kts
RELEASE_STORE_PASSWORD=qlink@123
RELEASE_KEY_ALIAS=q_link_key
RELEASE_KEY_PASSWORD=qlink@123
